### PR TITLE
cleaning and remove displays withAcl

### PR DESCRIPTION
**Pull request by bourgeoa**
@jeff-zucker 
I followed your conseil : I commented out the displays withAcl in index.html
Kept the code in solid-ide.js and changes in main.css

You can test it at https://bourgeoa.github.io/solid-ide/

### CODE REVIEW

**Comment by jeff-zucker** [comment]
Why does it default to showing .acl links?  It makes all folder reading
very slow.  My suggestion was that we not show any linked resources until
we have a way for users to create and edit those resources.

**Comment by bourgeoa** [comment]
Sorry it's an error

**Comment by jeff-zucker** [comment]
No problem.  And thanks for keeping the old code, we will hopefully put it
back into production sometime.  I wonder if it would be easy to have a
super-user mode (e.g. through an extra flag on the query string) such that
you and I could still use those features for testing but it wouldn't be a
part of the public interface.  I wouldn't waste a lot of time on it, but
it's an idea.

**Comment by bourgeoa** [comment]
No I check and it does not. may be you should reload or clear the browser

**Comment by jeff-zucker** [comment]
Ah, I'll have to be more careful about that, had to clear all the site data
and reload.

**Comment by jeff-zucker** [comment]
Something appears to be wrong.  I am logged in as me on my own pod and when
I try to delete something a "no access" message flashes over my console and
then disappears - no error popup, the delete fails.

**Comment by jeff-zucker** [comment]
Hmm, I re-logged in, and now it works.  So the problem isn't deleting, it's
that the options show  me as logged in when apparently I'm not.

**Pull request merged**
